### ISSUE TITLE
Comments from Huff Review

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-park-math-comp#3]
Some corrections based on #2 

- [x] There should be an abstract.
- [x] Particularly if there is no abstract, the introduction should say what the paper at hand contains/achieves. Having some background (as you do) is fine, but the introduction can't just be background. The reader should know very early in the document what the point of the document is going to be.
- [x] The "background of molten salt reactors" section gets a little broad. While some of this is reasonable, the paper would be better served by details regarding the MSFR, past work in simulating the MSFR, etc.
- [x] It seems you have not reviewed the writing checklist. The paper is in passive voice throughout, with many places where the active voice would be much clearer and more to the point (e.g. the sentence beginning with "The major component"
- [x] A proliferation of the word "of" in many sentences indicates places where adjectives could be combined to shorten and clarify ideas (e.g. "The MSFR consists of a central core region of volume 9m^3. The primary fuel salt... " would be clearer, "The primary fuel salt flows upward through the 9m^3 central core volume, ..."). Related, at this point in the paper, it's clear we're talking about the MSFR, so the frequent use of the reactor's name could be stricken from many sentences to simplify and clarify them.
- [x] Some grammatical issues "It can run on same... "
- [x] The thermal/electric power entry in the table is unusual Typically we describe this as the thermal efficiency (and invert it, such that we report electric/thermal).
- [x] Figure 2 is sufficiently simple that making it to scale shouldn't be a challenge. Why is it not to scale? Seems misleading.
- [x] Table 6 has drifted into the references. Please use \FloatBarrier to keep it in place (use the placeins package)
- [ ] I believe that the 4 page summary limit includes references. (but they likely won't reject you for going over...)
- [x] Every table should have three horizontal lines (top, under the column headings, and bottom). Please add top and bottom lines to all tables.
- [x] 6 groups is an unusual number of groups. Is there a reason you are using 6 groups? There's nothing really special about 8, but it's more common. Where did these group boundaries come from?
- [x] run a spellcheck (geiven)
- [x] I think the audience will be very lost regarding the disparity between the aim in the intro/motivation and the ultimate conclusion. Please bring these sections closer together, conceptually.

**Comment by katyhuff** [comment]
I'll be very impressed if you can. All of the comments that are questions should be answered here (I genuinely want to know the answers ).

**Comment by smpark7** [comment]
1) Figure 2 was not to scale because I saw that previous authors didn't always draw to scale. Also, the 2cm thickness of the blanket tank may not be visible relative to the 188cm total height of the geometry. I will make a figure to scale if I have the time, and decide which figure to go with.

2) I'm comparing my results with Pettersen's results and the energy boundaries are exactly the boundaries that he used. I will be more clear about this in writing.

**Comment by katyhuff** [comment]
You can ignore the figure scale if you're trying to meet the deadline tonight. But, for the full paper, I think it should be to scale unless there's a very compelling reason for it not to be.

**Comment by katyhuff** [comment]
Closed as won't fix. M&C paper withdrawn.
